services:
  idendity-api:
    build:
      context: .
      dockerfile: Idendity.Api/Dockerfile
    container_name: idendity-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=idendity-sqlserver;Database=IdendityDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      - RUN_MIGRATIONS=true
    depends_on:
      idendity-sqlserver:
        condition: service_healthy
    networks:
      - idendity-network

  idendity-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: idendity-sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"
    volumes:
      - idendity_sqlserver_data:/var/opt/mssql
    networks:
      - idendity-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  idendity-network:
    driver: bridge

volumes:
  idendity_sqlserver_data:
    driver: local